insert into car_model (modelID, model) values (1, 'Aspen');
insert into car_model (modelID, model) values (2, 'Forester');
insert into car_model (modelID, model) values (3, 'Legacy');
insert into car_model (modelID, model) values (4, 'CRV');
insert into car_model (modelID, model) values (5, 'Santa Fe');
insert into car_model (modelID, model) values (6, 'Chariot');
insert into car_model (modelID, model) values (7, 'Spyder');
insert into car_model (modelID, model) values (8, 'A3');
insert into car_model (modelID, model) values (9, 'Grand Marquis');
insert into car_model (modelID, model) values (10, 'Silverado');
insert into car_model (modelID, model) values (11, 'Legend');
insert into car_model (modelID, model) values (12, 'Ram');
insert into car_model (modelID, model) values (13, 'Titan');
insert into car_model (modelID, model) values (14, 'Sequoia');
insert into car_model (modelID, model) values (15, 'Cooper');
insert into car_model (modelID, model) values (16, 'Fiorano');
insert into car_model (modelID, model) values (17, 'Club Coupe');
insert into car_model (modelID, model) values (18, 'Elantra');
insert into car_model (modelID, model) values (19, 'Rio5');
insert into car_model (modelID, model) values (20, 'GTI');
