insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (1, 'Vagram', 'Everett', 'New Brunswick', 'New Jersey', 'United States', 'Ludovika Cammidge');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (2, 'Bamity', 'Kennedy', 'Pocatello', 'Idaho', 'United States', 'Kellen Bagley');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (3, 'Cookley', 'Eastwood', 'Hartford', 'Connecticut', 'United States', 'Melisandra Greeding');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (4, 'Overhold', 'Sachtjen', 'Boise', 'Idaho', 'United States', 'Norene Saunder');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (5, 'Stringtough', 'Meadow Vale', 'Fort Lauderdale', 'Florida', 'United States', 'Joey Curling');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (6, 'Y-Solowarm', 'Vera', 'Saint Louis', 'Missouri', 'United States', 'Stoddard Sulley');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (7, 'Redhold', 'Westerfield', 'Chicago', 'Illinois', 'United States', 'Renelle Jager');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (8, 'Hatity', 'Mesta', 'San Rafael', 'California', 'United States', 'Amata Anthon');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (9, 'Mat Lam Tam', 'Carpenter', 'Boston', 'Massachusetts', 'United States', 'Wilbur Giffin');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (10, 'Latlux', 'Walton', 'Philadelphia', 'Pennsylvania', 'United States', 'Ros Dumbreck');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (11, 'Tresom', 'School', 'Dallas', 'Texas', 'United States', 'Sheppard Troni');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (12, 'Opela', 'Colorado', 'Fort Wayne', 'Indiana', 'United States', 'Elmo Nason');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (13, 'Job', 'Ridgeway', 'Fort Wayne', 'Indiana', 'United States', 'Aigneis Pullan');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (14, 'Zamit', 'Sage', 'Columbus', 'Ohio', 'United States', 'Nonah Blackbrough');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (15, 'Wrapsafe', 'Roxbury', 'Topeka', 'Kansas', 'United States', 'Jerad De Benedictis');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (16, 'Stim', 'Ryan', 'Austin', 'Texas', 'United States', 'Martainn Rockliffe');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (17, 'Asoka', 'Bayside', 'Winston Salem', 'North Carolina', 'United States', 'Renado Normanvill');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (18, 'Andalax', 'Lindbergh', 'Richmond', 'Virginia', 'United States', 'Salim Thor');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (19, 'Overhold', 'Dayton', 'Oklahoma City', 'Oklahoma', 'United States', 'Jessy Town');
insert into Rental_Branch (rentalBranchID, branchName, address, city, state, country, branchManager) values (20, 'Alphazap', 'Village Green', 'Des Moines', 'Iowa', 'United States', 'Brooks Fittis');
